################################################
## Calibration of the Church Censorship Model
## Authors: Blasutto Fabio and David de la Croix
################################################

###PART-1: LOAD PACKAGES########
## remove (almost) everything in the working environment.
rm(list = ls())

#increase memory size
memory.limit(size=50000)

# to import xl files
library(readxl)

#to write excel files
require(writexl)

# to output towards latex
require(stargazer)

# for generating random variables
library(evd)

# for latex symbols in the graphs
library(latex2exp)

# genetic algorithm for estimation
library(GA)

# for a bootstraped CI
library(boot)

#extract from a word
library(tidyverse)

#For fancy graphs
library(tikzDevice)
library(ggplot2)

#For list sving
library(rlist)

#Set seed
set.seed(2)
###PART 0: WHICH SAMPLE/MODEL DO YOU WANT?#############################################
cmom<-TRUE    #want to redo-data part? 
serrors<-FALSE  #want to compute se for parameters?
nboots<-500    #Bootstrapping nummber


impbeta <<-1    #imperfectSqzr application of censorship-max 1/.78
maxper<<-5      #max number of periods to consider

ita<-FALSE      #only italian scholars
itan<-FALSE     #only northern italian scholars
itas<-FALSE     #only southern italian scholars
notonlyby<-FALSE#not only publications by person 
weak<-FALSE     #do not consider weak links
unio<-FALSE     #Only univresity, no academies
identif<-FALSE  #this serves for understanding how the model is identified
robc<-FALSE
wiki<-FALSE

if(impbeta>1){imperfect<-TRUE}else{imperfect<-FALSE}
if(maxper<5){maxt<-TRUE}else{maxt<-FALSE}
if(ita+itan+itas+notonlyby+maxt+imperfect+weak+robc+unio+wiki>0){normal<-FALSE}else{normal<-TRUE}

#Get name to print results
names<-c("ita","itan","itas","notonlyby","maxt","imperfect","weak","normal","robc","unio","wiki")
valll<-c(ita,itan,itas,notonlyby,maxt,imperfect,weak,normal,robc,unio,wiki)
namet<-which.max(valll)
nome<-names[namet]


###PART 1: GET THE DATA#############################################

if (cmom){
# set the directory to where the files are located
#setwd("C:\\Users\\ddlc\\Documents\\Dropbox\\01. Research\\UTHC main\\access database")
#setwd("C:\\Users\\blasutto\\Dropbox\\Roman_Church_censorship_growth\\big base\\old")
setwd("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\big base")

#load database 
basetot <- as.data.frame(read_excel("Profs.xlsx"))
dico <- as.data.frame(read_excel("dictionary.xlsx"))
basew  <- as.data.frame(read_excel("Profs-wiki-all.xlsx"))
membersa  <- as.data.frame(read_excel("Italian academies.xlsx"))
membersu  <- as.data.frame(read_excel("Italian universities.xlsx"))

if (unio){members<-membersu}else{members<-rbind(membersa,membersu)}


#setwd("C:\\Users\\ddlc\\Documents\\Dropbox\\01. Research\\Roman_Church_censorship_growth\\data_work")
setwd("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\data_work\\Fabio")
#setwd("C:\\Users\\blasutto\\Dropbox\\Roman_Church_censorship_growth\\data_work")

#removing people without worldcat
members <- members[members$Worldcat!="NA",]
basetot <- basetot[basetot$Worldcat!="NA",]

#remove if field of research is 9 ()
members <- members[members$Field!="9" ,] 
basetot <- basetot[basetot$Field!="9" ,] 

#removing people not yet checked
members <- members[members$Forbidden!=8888,]
members <- members[members$Forbidden!=7777,]
members$PKey<-members$Persons_PKey#<-



#


#Sample
if(weak){members<-members[members$WeakLink=="FALSE",]}
if(ita+itas+itan){members<-members[members$nation=="ITA",]}

#members<-members[members$nation=="ITA",]

#remove duplicates
members  <- members[!duplicated(members$Persons_PKey), ]
basew  <- basew[!duplicated(basew), ]
basetot  <- basetot[!duplicated(basetot$PKey), ]
#members  <- members[!members$IKey=="AcadTurin-1757",]

plist<-unique(members$Persons_PKey)


plist2<-basetot$PKey
#Find the performance in the base generated by the wiki routine

# take the index of quality
members$perfl <- 0
members$bypub <- 0
members$pubp <- 0
members$pubb <- 0
basetot$perfl <- 0
basew$public<- basew$public


#basew.pca <- prcomp(basew[,3:12], center = TRUE,scale. = TRUE)
for (j in plist){
  
  members[members$Persons_PKey==j,"EndDate"]<-basetot[basetot$PKey==j,"EndDate"]
  members[members$Persons_PKey==j,"perfl"] <- log(max(c(dico[dico$PKey==j,"publi_by"],1)))  # for individual quality
 

   if(notonlyby){
    members[members$Persons_PKey==j,"perfl"] <- log(max(c(dico[dico$PKey==j,"publications"],1)))
  }
  if(wiki){
    members[members$Persons_PKey==j,"perfl"] <- log(max(c(dico[dico$PKey==j,"LengthWikiN"],1)))
  }
  members[members$Persons_PKey==j,"pubb"] <- (c(dico[dico$PKey==j,"publications"]))
  members[members$Persons_PKey==j,"bypub"] <- (c(dico[dico$PKey==j,"publi_by"]))
  members[members$Persons_PKey==j,"pubp"] <- (c(dico[dico$PKey==j,"publi_about"]))
  members[members$Persons_PKey==j,"lat"] <- (c(basetot[basetot$PKey==j,"Locations_Latitude"]))[1]
}

for (j in plist2){
  basetot[basetot$PKey==j,"perfl"] <- log(max(c(basew[basew$PKey==j,"publications"],1)))  # for individual quality
  basetot[basetot$PKey==j,"pubb"] <- (c(basew[basew$PKey==j,"publications"])) 
}

nbase <- nrow(members)
for (i in (1:nbase)){
  members[i,"refdatel"] <- basew[basew$PKey==members[i,"PKey"],"refdatel"]
}
#North south of italy
if(itan){members<-members[members$lat>=43.8,]}
if(itas){members<-members[members$lat< 43.8,]}


members<-members[!is.na(members$perfl),]
basetot<-basetot[!is.na(basetot$perfl),]

if(!notonlyby){members<-members[members$bypub>0,]}
#if(wiki){members<-members[members$perfl>4.094345,]}

#we remove this guy who started in Spain and ended in Italy after 1750
#members <- members[members$PKey!="Pou-B-1727",]

#Get Nationality
members$nation<-substring(members$BirthPlace,nchar(members$BirthPlace)-2,nchar(members$BirthPlace))


members  <- members[members$refdatel>=1400,]
members  <- members[members$refdatel<1751,]
basetot  <- basetot[basetot$refdatel>=1400,]
basetot  <- basetot[basetot$refdatel<1750,]

################################################
# PART 2: COMPUTE THE MOMENTS
################################################

#We consider 5 periods here
members  <- members[members$refdatel>=1400,]
members  <- members[members$refdatel<1750,]





threshold0<- 1400
threshold1 <- 1470
threshold2 <- 1540
threshold3 <- 1610
threshold4<-1680
threshold5<-1750

members  <- members[members$refdatel>=threshold0,]
members  <- members[!members$refdatel>threshold5,]

members1 <- members[members$refdatel<threshold1,]
members2 <- members[threshold2>members$refdatel & members$refdatel>=threshold1,]
members3 <- members[threshold3>members$refdatel & members$refdatel>=threshold2,]
members4 <- members[threshold4>members$refdatel & members$refdatel>=threshold3,]
members5 <- members[members$refdatel>=threshold4,]


memberscensored1 <- members[members$Forbidden<9999 & members$refdatel<threshold1,]
membersnotcensored1 <- members[members$Forbidden==9999 & members$refdatel<threshold1,]

memberscensored2 <- members[members$Forbidden<9999 & 
                              threshold2>members$refdatel & members$refdatel>=threshold1,]
membersnotcensored2 <- members[members$Forbidden==9999 &
                                 threshold2>members$refdatel & members$refdatel>=threshold1,]

memberscensored3 <- members[members$Forbidden<9999 &
                              threshold3>members$refdatel & members$refdatel>=threshold2,]
membersnotcensored3 <- members[members$Forbidden==9999 &
                                 threshold3>members$refdatel & members$refdatel>=threshold2,]

memberscensored4 <- members[members$Forbidden<9999 &
                              threshold4>members$refdatel & members$refdatel>=threshold3,]
membersnotcensored4 <- members[members$Forbidden==9999  &
                                 threshold4>members$refdatel & members$refdatel>=threshold3,]


memberscensored5 <- members[members$Forbidden<9999 & members$refdatel>=threshold4,]
membersnotcensored5 <- members[members$Forbidden==9999 & members$refdatel>=threshold4,]

cenq<-c(mean(memberscensored1$perf),
        mean(memberscensored2$perfl),
        mean(memberscensored3$perfl),
        mean(memberscensored4$perfl),
        mean(memberscensored5$perfl))

ncenq<-c(mean(membersnotcensored1$perf),
         mean(membersnotcensored2$perfl),
         mean(membersnotcensored3$perfl),
         mean(membersnotcensored4$perfl),
         mean(membersnotcensored5$perfl))

q<-c(mean(members1$perf),
     mean(members2$perfl),
     mean(members3$perfl),
     mean(members4$perfl),
     mean(members5$perfl))

mcenq<-c(median(memberscensored1$perf),
         median(memberscensored2$perfl),
         median(memberscensored3$perfl),
         median(memberscensored4$perfl),
         median(memberscensored5$perfl))

mncenq<-c(median(membersnotcensored1$perf),
          median(membersnotcensored2$perfl),
          median(membersnotcensored3$perfl),
          median(membersnotcensored4$perfl),
          median(membersnotcensored5$perfl))

mq<-c(median(members1$perf),
      median(members2$perfl),
      median(members3$perfl),
      median(members4$perfl),
      median(members5$perfl))

memberscensored <- members[members$Forbidden<9999 ,]
membersnotcensored <- members[members$Forbidden==9999 ,]

maxperf<-round(max(members$perfl)+0.5,)
maxpeople<-100/2

maxperfd <- 2* maxperf

bv<-(0:maxperfd)
bv<-bv/2


# get the k_t,K^theta_R and m_t*beta_t in the data
Embeta<-numeric(length=5)
Eqr<-numeric(length=5)
ENC<-numeric(length=5)
Eqc<-numeric(length=5)
Eq<-numeric(length=5)
Em<-numeric(length=5)
EqrQ75<-numeric(length=5)
ENCQ75<-numeric(length=5)
EqQ75<-numeric(length=5)
EqrM<-numeric(length=5)
ENCM<-numeric(length=5)
EqM<-numeric(length=5)

for (i in 1:5) {
  
  nam <- paste("members", i, sep = "")
  namc <- paste("memberscensored", i, sep = "")
  namnc <- paste("membersnotcensored", i, sep = "")
  
  #compute means
  Embeta[i]<-length(get(namc)$perfl)/(length(get(namc)$perfl)+ length(get(namnc)$perfl))
  Eqr[i]=mean(get(namc)$perfl)
  ENC[i]=mean(get(namnc)$perfl)
  Eq[i]=mean(get(nam)$perfl)
  
  #compute medians
  EqrM[i]=median(get(namc)$perfl)
  ENCM[i]=median(get(namnc)$perfl)
  EqM[i]=median(get(nam)$perfl)
  
  #compute 75 percentile
  EqrQ75[i]=quantile(get(namc)$perfl,0.75)
  ENCQ75[i]=quantile(get(namnc)$perfl,0.75)
  EqQ75[i]=quantile(get(nam)$perfl,0.75)
  
  
  
}
rm(nam,namc,namnc)


sink("momentstofit.Rnw")

cat(paste('\\begin{table}[htbp]
	\\centering
\\begin{tabularx}{\\textwidth}{ l *{5}{Y}}
\\hline
\\hline
Moment description& \\multicolumn{5}{c}{Period}\\\\
   & 1400-70 &1470-1540 & 1540-1610 & 1610-80 & 1680-1750 \\\\\\cline{1-6}\\rule{-4pt}{2.5ex}
   Number of authors
    &  ',round(nrow(members1), digits=2),'      &  ',round(nrow(members2), digits=2),'       &  ',round(nrow(members3), digits=2),'      &  ',round(nrow(members4), digits=2),'     &  ',round(nrow(members5), digits=2),'  \\\\
   \\% censored scholars
    & ',round(Embeta[1], digits=2),'    & ',round(Embeta[2], digits=2),'     & ',round(Embeta[3], digits=2),'    & ',round(Embeta[4], digits=2),'   & ',round(Embeta[5], digits=2),' \\\\ 
\\rule{-4pt}{2.5ex}
  Log publications per scholar, median
    & ',round(EqM[1], digits=2),'    & ',round(EqM[2], digits=2),'     & ',round(EqM[3], digits=2),'    & ',round(EqM[4], digits=2),'   & ',round(EqM[5], digits=2),' \\\\    
\\rule{-4pt}{2.5ex}
Log publications per scholar, $75^{th}$ percentile
    & ',round(EqQ75[1], digits=2),'    & ',round(EqQ75[2], digits=2),'     & ',round(EqQ75[3], digits=2),'    & ',round(EqQ75[4], digits=2),'   & ',round(EqQ75[5], digits=2),' \\\\    
\\rule{-4pt}{2.5ex}
Log publications per (censored) scholar, median 
    & ',round(EqrM[1], digits=2),'    & ',round(EqrM[2], digits=2),'     & ',round(EqrM[3], digits=2),'    & ',round(EqrM[4], digits=2),'   & ',round(EqrM[5], digits=2),' \\\\    
\\rule{-4pt}{2.5ex}
Log publications per (censored) scholar, $75^{th}$ percentile
    & ',round(EqrQ75[1], digits=2),'    & ',round(EqrQ75[2], digits=2),'     & ',round(EqrQ75[3], digits=2),'    & ',round(EqrQ75[4], digits=2),'   & ',round(EqrQ75[5], digits=2),' \\\\    
\\hline
\\hline
\\end{tabularx}
	{\\raggedright Note: periods: 1:1400-70, 2:1470-1540, 3:1540-1610, 4:1610-80, 5:1680-1750 \\par}
\\caption{Moments to fit}\\label{table:momentstofit}
\\end{table}'))

sink()
Sweave("momentstofit.Rnw")

# get the variance of uality in the first period to get theta
Evar<-var(members1$perfl)
#setwd("C:\\Users\\blasutto\\Dropbox\\Roman_Church_censorship_growth\\calibration")
#setwd("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\calibration")
##################################
# get bootstraped CI for graph
##################################
ns<-length(members$perfl)
boots<-numeric(ns)
Bmbeta<-array(,c(5,nboots))
Bq<-array(,c(5,nboots))
BNC<-array(,c(5,nboots))
Bqr<-array(,c(5,nboots))
BqM<-array(,c(5,nboots))
BNCM<-array(,c(5,nboots))
BqrM<-array(,c(5,nboots))
Bq75<-array(,c(5,nboots))
BNC75<-array(,c(5,nboots))
Bqr75<-array(,c(5,nboots))

#aa<-replicate(nboots, sample(members, ns,replace=TRUE))
for(i in 1:nboots){
  
  
  boots<-as.data.frame(sample(members$Persons_PKey,ns,replace=TRUE))
  memb<-merge(boots,members,
              by.x='sample(members$Persons_PKey, ns, replace = TRUE)',
              by.y='Persons_PKey')
  
  # compute what we need
  #memb<-members[boots%in% members$Persons_PKey]
  #memb<-subset(members,members$Persons_PKey==boots)
  
  #We consider 4 periods here
  members1 <- memb[memb$refdatel<threshold1,]
  members2 <- memb[threshold2>memb$refdatel & memb$refdatel>=threshold1,]
  members3 <- memb[threshold3>memb$refdatel & memb$refdatel>=threshold2,]
  members4 <- memb[threshold4>memb$refdatel & memb$refdatel>=threshold3,]
  members5 <- memb[memb$refdatel>=threshold4,]
  
  memberscensored1 <- memb[memb$Forbidden<9999 & memb$refdatel<threshold1,]
  membersnotcensored1 <- memb[memb$Forbidden==9999 & memb$refdatel<threshold1,]
  
  memberscensored2 <- memb[memb$Forbidden<9999 & 
                             threshold2>memb$refdatel & memb$refdatel>=threshold1,]
  membersnotcensored2 <- memb[memb$Forbidden==9999 &
                                threshold2>memb$refdatel & memb$refdatel>=threshold1,]
  
  memberscensored3 <- memb[memb$Forbidden<9999 &
                             threshold3>memb$refdatel & memb$refdatel>=threshold2,]
  membersnotcensored3 <- memb[memb$Forbidden==9999 &
                                threshold3>memb$refdatel & memb$refdatel>=threshold2,]
  
  memberscensored4 <- memb[memb$Forbidden<9999 &
                             threshold4>memb$refdatel & memb$refdatel>=threshold3,]
  membersnotcensored4 <- memb[memb$Forbidden==9999  &
                                threshold4>memb$refdatel & memb$refdatel>=threshold3,]
  
  memberscensored5 <- memb[memb$Forbidden<9999 & memb$refdatel>=threshold4,]
  membersnotcensored5 <- memb[memb$Forbidden==9999 & memb$refdatel>=threshold4,]
  
  
  memberscensored <- memb[memb$Forbidden<9999 ,]
  
  
  #the moments now
  for(j in 1:5){
    
    nam <- paste("members", j, sep = "")
    namc <- paste("memberscensored", j, sep = "")
    namnc <- paste("membersnotcensored", j, sep = "")
    
    Bmbeta[j,i]<-length(get(namc)$perfl)/(length(get(namc)$perfl)+ length(get(namnc)$perfl))
    Bqr[j,i]=mean(get(namc)$perfl)
    Bq[j,i]=mean(get(nam)$perfl)
    BNC[j,i]=mean(get(namnc)$perfl)
    BqrM[j,i]=median(get(namc)$perfl)
    BqM[j,i]=median(get(nam)$perfl)
    BNCM[j,i]=median(get(namnc)$perfl)
    Bqr75[j,i]=quantile(get(namc)$perfl,0.75)
    Bq75[j,i]=quantile(get(nam)$perfl,0.75)
    BNC75[j,i]=quantile(get(namnc)$perfl,0.75)
    
  }}

#get finally the CI
CImbeta<-array(,c(2,5))
CIq<-array(,c(2,5))
CIqr<-array(,c(2,5))
CINC<-array(,c(2,5))
CImbeta75<-array(,c(2,5))
CIq75<-array(,c(2,5))
CIqr75<-array(,c(2,5))
CINC75<-array(,c(2,5))

for(j in 1:5){
  CImbeta[,j]<-quantile(Bmbeta[j,],c(0.025,0.975))
  CIq[,j]<-quantile(BqM[j,],c(0.025,0.975))
  CIqr[,j]<-quantile(BqrM[j,],c(0.025,0.975))
  CINC[,j]<-quantile(BNCM[j,],c(0.025,0.975))
  CIq75[,j]<-quantile(Bq75[j,],c(0.025,0.975))
  CIqr75[,j]<-quantile(Bqr75[j,],c(0.025,0.975))
  CINC75[,j]<-quantile(BNC75[j,],c(0.025,0.975))
  
}

#Save and store the results
Bqc<-BNC
Bm<-Bmbeta
momentss<-list("Embeta"=Embeta,"Eqr"=Eqr,
               "ENC"=ENC,"Eqc"=Eqc,
               "Em"=Em,"EqrQ75"=EqrQ75,
               "ENCQ75"=ENCQ75,"EqQ75"=EqQ75,
               "EqrM"=EqrM,"ENCM"=ENCM,
               "Bmbeta"=Bmbeta,"Bqr"=Bqr,
               "BNC"=BNC,"Bqc"=Bqc,
               "Bm"=Bm,"Bqr75"=Bqr75,
               "BNC75"=BNC75,"Bq75"=Bq75,
               "BqrM"=BqrM,"BNCM"=BNCM,
               "EqM"=EqM,"CImbeta"=CImbeta,
               "CIq"=CIq,"CIqr"=CIqr,
               "CINC"=CINC,"CIq75"=CIq75,
               "CIqr75"=CIqr75,"CINC75"=CINC75,
               "Eq"=Eq,
               "GAs"="none")



list.save(momentss, 'data.Rdata')  


}else{
  #Load results
  setwd("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\data_work\\Fabio")
  mbau<-list.load("data.Rdata")
  
 # for (j in 1:30){print(max(momentss[[j]]-mbau[[j]]))}
    
    
    
  
  
  assign(names(mbau)[1],mbau[[1]])
  assign(names(mbau)[2],mbau[[2]])
  assign(names(mbau)[3],mbau[[3]])
  assign(names(mbau)[4],mbau[[4]])
  assign(names(mbau)[5],mbau[[5]])
  assign(names(mbau)[6],mbau[[6]])
  assign(names(mbau)[7],mbau[[7]])
  assign(names(mbau)[8],mbau[[8]])
  assign(names(mbau)[9],mbau[[9]])
  assign(names(mbau)[10],mbau[[10]])
  assign(names(mbau)[11],mbau[[11]])
  assign(names(mbau)[12],mbau[[12]])
  assign(names(mbau)[13],mbau[[13]])
  assign(names(mbau)[14],mbau[[14]])
  assign(names(mbau)[15],mbau[[15]])
  assign(names(mbau)[16],mbau[[16]])
  assign(names(mbau)[17],mbau[[17]])
  assign(names(mbau)[18],mbau[[18]])
  assign(names(mbau)[19],mbau[[19]])
  assign(names(mbau)[20],mbau[[20]])
  assign(names(mbau)[21],mbau[[21]])
  assign(names(mbau)[22],mbau[[22]])
  assign(names(mbau)[23],mbau[[23]])
  assign(names(mbau)[24],mbau[[24]])
  assign(names(mbau)[25],mbau[[25]])
  assign(names(mbau)[26],mbau[[26]])
  assign(names(mbau)[27],mbau[[27]])
  assign(names(mbau)[28],mbau[[28]])
  assign(names(mbau)[29],mbau[[29]])
  assign(names(mbau)[30],mbau[[30]])

}


###PART 2: ESTIMATION#################################################


t<-numeric()
v<-numeric()
pe<-numeric()
z0<-numeric()
up<-numeric()
Sqc<-numeric(length=5)
Sqr<-numeric(length=5)
SNC<-numeric(length=5)
SNC75<-numeric(length=5)
Sq<-numeric(length=5)
pre<-numeric()
pre1<-numeric()
pre2<-numeric()
i<-numeric()
thet<-numeric()
eqrt<-numeric()
eqt<-numeric()
eqrtt<-numeric()
eqct<-numeric()
# match initial conditions


# some functions to get the simulated variables

f<-function(x,the,k,pr,eqt,eqrt) {
  
  -eqt+(((eqrt/x)^(1/the))/((eqrt/x)^(1/the)+pr))*eqrt+
    (1-(((eqrt/x)^(1/the))/((eqrt/x)^(1/the)+pr)))*x}

fm<-function(x,the,k,pr,eqt,eqrt) {
  
  -eqt+(((eqrt/x)^(1/the))/((eqrt/x)^(1/the)+pr))*eqrt+
    (1-(((eqrt/x)^(1/the))/((eqrt/x)^(1/the)+pr)))*x}

fq<-function(the,pr,eqct,eqrt) {
  
  zeta=(eqrt/eqct)^(1/the)
  emma=zeta/(zeta+pr)

  (emma)*eqrt+(1-emma)*eqct}
 

zt<-function(beta,pe,t,up,thet,eqct,eqrtt) {
  
  # get z0 first
  #v=uniroot(f,c(0.00001,up),tol=0.00000001,maxiter=10000,the=thet,k=1,
  #          pr=pe,eqt=eqtt,eqrt=eqrtt)
  #z0=(eqrtt/v$root)^(1/thet)
  z0=(eqrtt/eqct)^(1/thet)
  if(t>2){
    z0=pe/(1)*(z0*(1)/pe)^(2)
    pe/(1-beta)*(z0*(1-beta)/pe)^(2^(t-2))}else if(t==2){pe/(1)*(z0*(1)/pe)^(2^(t-1))}else{z0}}


mt<-function(beta,pr,t,up,thet,eqct,eqrtt) zt(beta,pr,t,up,thet,eqct,eqrtt)/(pr+zt(beta,pr,t,up,thet,eqct,eqrtt))

mbetat<-function(beta,pr,t,up,thet,eqct,eqrtt) beta*impbeta*mt(beta,pr,t,up,thet,eqct,eqrtt)

qrs<-function(beta,pe,t,up,mu,pre,thet,eqct,eqrtt) if(t<=2){gamma(1-thet)*(mu*((1)*(pre/gamma(1-thet))^(1/thet)*
                                                                                 (mt(0,pe,t-1,up,thet,eqct,eqrtt))))^thet}else
                                                                                 {gamma(1-thet)*(mu*((1-beta)*(pre/gamma(1-thet))^(1/thet)*
                                                                                                       (mt(beta,pe,t-1,up,thet,eqct,eqrtt))))^thet} 


qcs<-function(beta,pe,t,up,mu,pre,thet,eqct,eqrtt) if(t<=2){gamma(1-thet)*((mu*((pre/gamma(1-thet))^(1/thet)*
                                                                                  (1-mt(0,pe,t-1,up,thet,eqct,eqrtt)))))^thet}else
                                                                                  {gamma(1-thet)*((mu*((pre/gamma(1-thet))^(1/thet)*
                                                                                                         (1-mt(beta,pe,t-1,up,thet,eqct,eqrtt)))))^thet}             


qs<-function(beta,pe,t,up,mu,pre1,pre2,thet,eqct,eqrtt) if(t<=2){qrs(0,pe,t,up,mu,pre1,thet,eqct,eqrtt)*mt(0,pe,t,up,thet,eqct,eqrtt)+
    (1-mt(0,pe,t,up,thet,eqct,eqrtt))*qcs(0,pe,t,up,mu,pre2,thet,eqct,eqrtt)}else
    {qrs(beta,pe,t,up,mu,pre1,thet,eqct,eqrtt)*mt(beta,pe,t,up,thet,eqct,eqrtt)+
        (1-mt(beta,pe,t,up,thet,eqct,eqrtt))*qcs(beta,pe,t,up,mu,pre2,thet,eqct,eqrtt)}

nc<-function(beta,pe,t,up,mu,pre1,pre2,thet,eqct,eqrtt) if(t<=2){qrs(0,pe,t,up,mu,pre1,thet,eqct,eqrtt)*
    (((1)*mt(0,pe,t,up,thet,eqct,eqrtt))/(1))+
    ((1-mt(0,pe,t,up,thet,eqct,eqrtt))/(1))*
    qcs(0,pe,t,up,mu,pre2,thet,eqct,eqrtt)}else
    {qrs(beta,pe,t,up,mu,pre1,thet,eqct,eqrtt)*
        (((1-beta)*mt(beta,pe,t,up,thet,eqct,eqrtt))/(1-beta*mt(beta,pe,t,up,thet,eqct,eqrtt)))+
        ((1-mt(beta,pe,t,up,thet,eqct,eqrtt))/(1-beta*mt(beta,pe,t,up,thet,eqct,eqrtt)))*
        qcs(beta,pe,t,up,mu,pre2,thet,eqct,eqrtt)}



#GUARDA A INITIAL CONDITION CIU C

# define the function that we want to minimize taking beta
maxg<-100
max<-numeric()
maxx<-numeric()
muu<-numeric()
betaa<-numeric()
sum<-numeric(length=1)
MT<-numeric()
MR<-numeric()
MT75<-numeric()
MR75<-numeric()
upper<-seq(0.01,200,length.out=maxg)
qu<-numeric()
qur<-numeric()

# compute empirical and non empirical
n<-1000#how many draws from distribution
B=numeric(length=n)
B1=numeric(length=n)
Bc=numeric(length=n)
Br=numeric(length=n)
set.seed(2)
B1=runif(n, min = 0, max = 1)  # shocks for deciding later from which distribution to draw



#parameters for the simulation

mini<-function(betaa,pee,muu,thet,qu,qur){
  
  sum=0     
  pe<-exp(pee)
  Sqr[1]=qur
  Sqc[1]=qu
  Sq[1]=fq(thet,pe,Sqc[1],Sqr[1])
  
  
  
  for(i in 1:maxper){
    if(i>=2){
      
      Sqc[i]<-qcs(betaa,pe,i,maxx,muu,Sqc[i-1],thet,Sqc[1],Sqr[1])
      Sqr[i]<-qrs(betaa,pe,i,maxx,muu,Sqr[i-1],thet,Sqc[1],Sqr[1])
      Sq[i] <-qs(betaa,pe,i,maxx,muu,Sqr[i-1],Sqc[i-1],thet,Sqc[1],Sqr[1])          
      
    }}
  
  
  
  
  
  for (i in 1:maxper){
    mcur<-mt(betaa,pe,i,maxx,thet,Sqc[1],Sqr[1])        
    
    
    
    
    if(i>=2){
      
      sum=sum+((mcur*betaa*impbeta-Embeta[i])/Embeta[i])^2
      #Moments with median
     
      MR[i]<-(((qrs(betaa,pe,i,maxx,muu,Sqr[i-1],thet,Sqc[1],Sqr[1])/(gamma(1-thet)))^(1/1))/
                ((log(2))^thet))
      
      #Model with 75p
     
      MR75[i]<-(((qrs(betaa,pe,i,maxx,muu,Sqr[i-1],thet,Sqc[1],Sqr[1])/(gamma(1-thet)))^(1/1))/
                  ((log(4/3))^thet))
      
      # draw random realization from the two frechet distibutions
      set.seed(2)
      Br=rfrechet(n, loc=0, scale=Sqr[i]/(gamma(1-thet)),shape=1/thet)
      set.seed(2)
      Bc=rfrechet(n, loc=0, scale=Sqc[i]/(gamma(1-thet)),shape=1/thet)
      pr<-mcur#*(1-betaa)/(1-betaa*mcur)
      for (j in 1:n) {if (B1[j]>pr) {B[j]=Bc[j]} else {B[j]=Br[j]}}
      MT[i]=median(B)
      MT75[i]=quantile(B,0.75)
      
      #Moments with average
      #MT[i]<-qs(betaa,pe,i,maxx,muu,Sqr[i-1],Sqc[i-1],thet,Sq[1],Sqr[1])
      #MR[i]<-qrs(betaa,pe,i,maxx,muu,Sqr[i-1],thet,Sq[1],Sqr[1])
      
      
      sum=sum+((MT[i]-EqM[i])/EqM[i])^2
      sum=sum+((MT75[i]-EqQ75[i])/EqQ75[i])^2
      #=sum+((MR[i]-EqrM[i])/EqrM[i])^2
      #sum=sum+((MR75[i]-EqrQ75[i])/EqrQ75[i])^2
      
      
      
    }else{
      
      #Median 
     
      MR[1]<-(((Sqr[1]/(gamma(1-thet)))^(1/1))/
                ((log(2))^thet))
      
      #75 percentile
     
      MR75[1]<-(((Sqr[1]/(gamma(1-thet)))^(1/1))/
                  ((log(4/3))^thet))
      
      # draw random realization from the two frechet distibutions
      set.seed(2)
      Br=rfrechet(n, loc=0, scale=Sqr[i]/(gamma(1-thet)),shape=1/thet)
      set.seed(2)
      Bc=rfrechet(n, loc=0, scale=Sqc[i]/(gamma(1-thet)),shape=1/thet)
      pr<-mcur#*(1-betaa)/(1-betaa*mcur)
      for (j in 1:n) {if (B1[j]>pr) {B[j]=Bc[j]} else {B[j]=Br[j]}}
      MT[i]=median(B)
      MT75[i]=quantile(B,0.75)
      
      #Average
      #MT[1]<-Sq[1]
      #MR[1]<-Sqr[1]
      
      sum=sum+((MT[1]-EqM[1])/EqM[1])^2
      sum=sum+((MT75[1]-EqQ75[1])/EqQ75[1])^2
      #sum=sum+((MR[1]-EqrM[1])/EqrM[1])^2
      #sum=sum+((MR75[1]-EqrQ75[1])/EqrQ75[1])^2
    }}
  
  # if(mt(betaa,pe,1,maxx,thet)<0.5){sum=10000}      
  
  return(sum)}


ff<-function(x) -mini(x[1],x[2],x[3],x[4],x[5],x[6])



# call the genetic alogorithm for the estimation
GA <- ga(type = "real-valued", 
         fitness = ff, 
         lower = c(0.12,1.7,1.0,0.05,3.5-0.35,Eqr[1]-0.4),
         upper = c(0.25,2.5,4  ,0.45,3.5+0.4 ,Eqr[1]+0.4),
         popSize = 100, maxiter = 180, run = 50,
         elitism = max(1, round(200*0.15)),
         optim=FALSE,
         seed=1,
         optimArgs = list(method = "L-BFGS-B",poptim = 0.2,pressel = 0.5,
                          control = list(fnscale = -1, maxit = 20)))

# visualize the solution 
summary(GA)
plot(GA)

beta<-GA@solution[1,1]
p<-exp(GA@solution[1,2])
mu<-GA@solution[1,3]
theta<-GA@solution[1,4]
Sqr[1]<-GA@solution[1,6]
Sq[1]<-fq(theta,p,GA@solution[1,5],Sqr[1])
Sqc[1]<-GA@solution[1,5]



###PART 3: Simulation + graphs########################################################

betaT<-numeric(length = )





Smbeta=numeric(length=5)
Sz=numeric(length=5)
Sm=numeric(length=5)
Ez=numeric(length=5)
Em=numeric(length=5)
SqrM<-numeric(length=5)
SNCM<-numeric(length=5)
SqM<-numeric(length=5)
SqrQ75<-numeric(length=5)
SNCQ75<-numeric(length=5)
SqQ75<-numeric(length=5)
max<-1
betat<-beta



for(i in 1:5){
  
  
  Sm[i]=mt(betat,p,i,max,theta,Sqc[1],Sqr[1])
  Sz[i]=zt(betat,p,i,max,theta,Sqc[1],Sqr[1])
  Eqc[1]=Sqc[1]
  Sqc[1]=Eqc[1]
  Ez[i]=(Eqr[i]/Eqc[i])^(1/theta)
  Em[i]=Ez[i]/(p+Ez[i])
  Smbeta[i]=betat*mt(betat,p,i,max,theta,Sqc[1],Sqr[1])
  

  
  
  if(i>=2 ){
    
    Sqc[i]=qcs(betat,p,i,max,mu,Sqc[i-1],theta,Sqc[1],Sqr[1])
    Sqr[i]=qrs(betat,p,i,max,mu,Sqr[i-1],theta,Sqc[1],Sqr[1])
    Sq[i]=qs(betat,p,i,max,mu,Sqr[i-1],Sqc[i-1],theta,Sqc[1],Sqr[1])
    SNC[i]=nc(betat,p,i,max,mu,Sqr[i-1],Sqc[i-1],theta,Sqc[1],Sqr[1])
    
    #Below ONLY IF WE CONSIDER SHORT ESTIMATION PERIOD#
    if(maxper<5 & i==5){
      Smbeta[5]=betat*mt(betat,p,i,max,theta,Sqc[4],Sqr[4])
      betat<-0
      Sm[i]=mt(betat,p,2,max,theta,Sqc[4],Sqr[4])
      Sqc[i]=qcs(betat,p,2,max,mu,Sqc[4],theta,Sqc[4],Sqr[4])
      Sqr[i]=qrs(betat,p,2,max,mu,Sqr[4],theta,Sqc[4],Sqr[4])
      Sq[i]=qs(betat,p,2,max,mu,Sqr[4],Sqc[4],theta,Sqc[4],Sqr[4])
      SNC[i]=nc(betat,p,2,max,mu,Sqr[4],Sqc[4],theta,Sqc[4],Sqr[4])
      
     
      
    }
    
    #median
    SqM[i]=(((Sq[i]/(gamma(1-theta)))^(1/1))/
              ((log(2))^theta))
    SqrM[i]=(((Sqr[i]/(gamma(1-theta)))^(1/1))/
               ((log(2))^theta))
    SqQ75[i]=(((Sq[i]/(gamma(1-theta)))^(1/1))/
                ((log(4/3))^theta))
    SqrQ75[i]=(((Sqr[i]/(gamma(1-theta)))^(1/1))/
                 ((log(4/3))^theta))
    
    # draw random realization from the two frechet distibutions
    Br=rfrechet(n, loc=0, 
                scale=(qrs(betat,p,i,max,mu,Sqr[i-1],theta,Sqc[1],Sqr[1])/(gamma(1-theta))),
                shape=1/theta)
    
    Bc=rfrechet(n, loc=0, 
                scale=qcs(betat,p,i,max,mu,Sqc[i-1],theta,Sqc[1],Sqr[1])/(gamma(1-theta)),
                shape=1/theta)
    
    pr<-Sm[i]*(1-betat)/(1-betat*Sm[i])
    for (j in 1:n) {if (B1[j]>pr) {B[j]=Bc[j]} else {B[j]=Br[j]}}
    SNCM[i]=median(B)
    SNCQ75[i]=quantile(B,0.75)
    
    pr<-Sm[i]#*(1-betat)/(1-betat*Sm[i])
    for (j in 1:n) {if (B1[j]>pr) {B[j]=Bc[j]} else {B[j]=Br[j]}}
    SqM[i]=median(B)
    SqQ75[i]=quantile(B,0.75)
    
    
    
  }else{
    
    
    
    
    
    #SqQ75[1]=(((Sq[1]/(gamma(1-theta)))^(1/1))/
    #           ((log(4/3))^theta))
    SqrQ75[1]=(((Sqr[1]/(gamma(1-theta)))^(1/1))/
                 ((log(4/3))^theta))
    #SqM[1]=(((Sq[1]/(gamma(1-theta)))^(1/1))/
    #         ((log(2))^theta))
    SqrM[1]=(((Sqr[1]/(gamma(1-theta)))^(1/1))/
               ((log(2))^theta))
    SNC[1]=Sqr[1]*
      (((1)*mt(betat,p,i,max,theta,Sqc[1],Sqr[1]))/(1))+
      ((1-mt(betat,p,i,max,theta,Sqc[1],Sqr[1]))/(1))*
      Sqc[1]
    
    # draw random realization from the two frechet distibutions
    Br=rfrechet(n, loc=0, 
                scale=Sqr[1]/(gamma(1-theta)),
                shape=1/theta)
    
    Bc=rfrechet(n, loc=0, 
                scale=Sqc[1]/gamma(1-theta),
                shape=1/theta)
    
    pr<-Sm[i]
    for (j in 1:n) {if (B1[j]>pr) {B[j]=Bc[j]} else {B[j]=Br[j]}}
    
    SNCM[1]=median(B)
    SNCQ75[1]=quantile(B,0.75)
    SqM[1]=median(B)
    SqQ75[1]=quantile(B,0.75)
    
  }
  
}
  






# graph to visualize the reults
setwd("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\paper")
if(normal){
  
  ###############################
  #Graph Q50+Q75
  ################################
  time=seq(1,5,1) 
  q.df<- data.frame(time, EqM,SqM,EqQ75,SqQ75,CIq[1,],CIq[2,],CIq75[1,],CIq75[2,])
  
  tikz(file = "q.tex", width = 5, height = 5)
  
  #Simple plot of the dummy data using LaTeX elements
  plot <- ggplot(q.df, aes(x = time)) + 
    geom_ribbon(aes(ymin = CIq.1..., ymax = CIq.2...), fill = "red",alpha=0.15)+
    geom_line(aes(y = EqM), color = "red",size=2) + 
    geom_line(aes(y = SqM), color="red", linetype="dashed",size=2) +
    geom_ribbon(aes(ymin = CIq75.1..., ymax = CIq75.2...), fill = "blue",alpha=0.15)+
    geom_line(aes(y = EqQ75), color = "blue",size=2) + 
    geom_line(aes(y = SqQ75), color="blue", linetype="dashed",size=2) +
    #Space does not appear after Latex 
    
    labs( x = "Time", y = "Knowledge Quality") +
    
    ylim(2.9, 9)+
    
    theme_classic(
      base_family = "",
      base_line_size = 1/22,
      base_rect_size = 1/22)+
    theme(
      axis.title.y = element_blank(),
      axis.title.x = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      #axis.title.y = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0)),
      axis.text.x  = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      axis.text.y  = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0))
    )
  
  #Necessary to close or the tikxDevice .tex file will not be written
  print(plot)
  dev.off()
  
  ###############################
  #Graph Qr50+Qr75
  ################################
  qr.df<- data.frame(time, EqrM,SqrM,EqrQ75,SqrQ75,CIqr[1,],CIqr[2,],CIqr75[1,],CIqr75[2,])
  
  tikz(file = "qr.tex", width = 5, height = 5)
  
  #Simple plot of the dummy data using LaTeX elements
  plot <- ggplot(qr.df, aes(x = time)) + 
    geom_ribbon(aes(ymin = CIqr.1..., ymax = CIqr.2...), fill = "red",alpha=0.15)+
    geom_line(aes(y = EqrM), color = "red",size=2) + 
    geom_line(aes(y = SqrM), color="red", linetype="dashed",size=2) +
    geom_ribbon(aes(ymin = CIqr75.1..., ymax = CIqr75.2...), fill = "blue",alpha=0.15)+
    geom_line(aes(y = EqrQ75), color = "blue",size=2) + 
    geom_line(aes(y = SqrQ75), color="blue", linetype="dashed",size=2) +
    geom_rect(aes(xmin=1,
                  xmax =2,
                  ymin = -Inf,
                  ymax = Inf), fill = 'white') +
    #Space does not appear after Latex 
    
    labs( x = "Time", y = "Knowledge Quality") +
    
    ylim(2.9, 9)+
    
    theme_classic(
      base_family = "",
      base_line_size = 1/22,
      base_rect_size = 1/22)+
    theme(
      axis.title.y = element_blank(),
      axis.title.x = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      #axis.title.y = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0)),
      axis.text.x  = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      axis.text.y  = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0))
    )
  
  #Necessary to close or the tikxDevice .tex file will not be written
  print(plot)
  dev.off()
  
  
  ###############################
  #Graph Qr50+Qr75
  ################################
  qnc.df<- data.frame(time, ENCM,SNCM,ENCQ75,SNCQ75,CINC[1,],CINC[2,],CINC75[1,],CINC75[2,])
  
  tikz(file = "qnc.tex", width = 5, height = 5)
  
  #Simple plot of the dummy data using LaTeX elements
  plot <- ggplot(qnc.df, aes(x = time)) + 
    geom_ribbon(aes(ymin = CINC.1..., ymax = CINC.2...), fill = "red",alpha=0.15)+
    geom_line(aes(y = ENCM), color = "red",size=2) + 
    geom_line(aes(y = SNCM), color="red", linetype="dashed",size=2) +
    geom_ribbon(aes(ymin = CINC75.1..., ymax = CINC75.2...), fill = "blue",alpha=0.15)+
    geom_line(aes(y = ENCQ75), color = "blue",size=2) + 
    geom_line(aes(y = SNCQ75), color="blue", linetype="dashed",size=2) +
    geom_rect(aes(xmin=1,
                  xmax =2,
                  ymin = -Inf,
                  ymax = Inf), fill = 'white') +
    #Space does not appear after Latex 
    
    labs( x = "Time", y = "Knowledge Quality") +
    
    ylim(2.9, 9)+
    
    theme_classic(
      base_family = "",
      base_line_size = 1/22,
      base_rect_size = 1/22)+
    theme(
      axis.title.y = element_blank(),
      axis.title.x = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      #axis.title.y = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0)),
      axis.text.x  = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      axis.text.y  = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0))
    )
  
  #Necessary to close or the tikxDevice .tex file will not be written
  print(plot)
  dev.off()
  
  ###############################
  #Graph Qr50+Qr75
  ################################
  Embeta<-Embeta*100
  Smbeta<-Smbeta*100*impbeta
  CImbeta<-CImbeta*100
  b.df<- data.frame(time, Embeta,Smbeta,CImbeta[1,],CImbeta[2,])
  
  tikz(file = "b.tex", width = 5, height = 5)
  
  #Simple plot of the dummy data using LaTeX elements
  plot <- ggplot(b.df, aes(x = time)) + 
    geom_ribbon(aes(ymin = CImbeta.1..., ymax = CImbeta.2...), fill = "darkgrey",alpha=0.2)+
    geom_line(aes(y = Embeta), color = "darkgrey",size=2) + 
    geom_line(aes(y = Smbeta), color="darkgrey", linetype="dashed",size=2) +
    geom_rect(aes(xmin=1,
                  xmax =2,
                  ymin = -Inf,
                  ymax = Inf), fill = 'white') +
    #Space does not appear after Latex 
    
    labs( x = "Time", y = "\\% censored authors") +
    
    
    theme_classic(
      base_family = "",
      base_line_size = 1/22,
      base_rect_size = 1/22)+
    theme(
      axis.title.y = element_blank(),
      axis.title.x = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      #axis.title.y = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0)),
      axis.text.x  = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      axis.text.y  = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0))
    )
  
  #Necessary to close or the tikxDevice .tex file will not be written
  print(plot)
  dev.off()
  
}



###PART 4: counterfactual experiment: no censorship##################

SzC=numeric(length=5)
SmC=numeric(length=5)
SmbetaC=numeric(length=5)
SqcC=numeric(length=5)
SqrC=numeric(length=5)
SqC=numeric(length=5)
for(i in 1:5){
  
  SmC[i]=mt(0,p,i,max,theta,Sqc[1],Sqr[1])
  SzC[i]=zt(0,p,i,max,theta,Sqc[1],Sqr[1])
  SmbetaC[i]=mbetat(0,p,i,max,theta,Sqc[1],Sqr[1])
  
  
  if(i>=2){
    
    SqcC[i]=qcs(0,p,i,max,mu,SqcC[i-1],theta,Sqc[1],Sqr[1])
    SqrC[i]=qrs(0,p,i,max,mu,SqrC[i-1],theta,Sqc[1],Sqr[1])
    SqC[i]=qs(0,p,i,max,mu,SqrC[i-1],SqcC[i-1],theta,Sqc[1],Sqr[1])
  }else{
    
    SqcC[1]=Sqc[1]
    SqC[1]=Sq[1]
    SqrC[1]=Sqr[1]}}


if(normal){
  ###############################
  #Graph bm
  ################################
  SmbetaC<-SmbetaC*100
  Smbeta<-Smbeta*0
  bmc.df<- data.frame(time, Smbeta,SmbetaC)
  
  tikz(file = "bmc.tex", width = 5, height = 5)
  
  #Simple plot of the dummy data using LaTeX elements
  plot <- ggplot(b.df, aes(x = time)) + 
    geom_line(aes(y = Smbeta), color = "darkgrey",size=2) + 
    geom_line(aes(y = SmbetaC), color="darkgrey", linetype="dashed",size=2) +
    geom_rect(aes(xmin=1,
                  xmax =2,
                  ymin = -Inf,
                  ymax = Inf), fill = 'white') +
    #Space does not appear after Latex 
    
    labs( x = "Time") +
    
    
    theme_classic(
      base_family = "",
      base_line_size = 1/22,
      base_rect_size = 1/22)+
    theme(
      axis.title.y = element_blank(),
      axis.title.x = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      #axis.title.y = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0)),
      axis.text.x  = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      axis.text.y  = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0))
    )
  
  #Necessary to close or the tikxDevice .tex file will not be written
  print(plot)
  dev.off()
  
  
  ###############################
  #Graph m
  ################################
  SmC<-SmC*100
  Sm<-Sm*100
  bc.df<- data.frame(time, Sm,SmC)
  
  tikz(file = "bc.tex", width = 5, height = 5)
  
  #Simple plot of the dummy data using LaTeX elements
  plot <- ggplot(bc.df, aes(x = time)) + 
    geom_line(aes(y = Sm), color = "darkgrey",size=2) + 
    geom_line(aes(y = SmC), color="darkgrey", linetype="dashed",size=2) +
    #Space does not appear after Latex 
    
    labs( x = "Time") +
    
    
    theme_classic(
      base_family = "",
      base_line_size = 1/22,
      base_rect_size = 1/22)+
    theme(
      axis.title.y = element_blank(),
      axis.title.x = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      #axis.title.y = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0)),
      axis.text.x  = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      axis.text.y  = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0))
    )
  
  #Necessary to close or the tikxDevice .tex file will not be written
  print(plot)
  dev.off()
  
  ###############################
  #Graph sq
  ################################
  sq.df<- data.frame(time, Sq,SqC,Sqr,SqrC,Sqc,SqcC)
  
  tikz(file = "sq.tex", width = 5, height = 5)
  
  #Simple plot of the dummy data using LaTeX elements
  plot <- ggplot(b.df, aes(x = time)) + 
    geom_line(aes(y = Sqr), color ="red",size=2) + 
    geom_line(aes(y = SqrC), color="red", linetype="dashed",size=2) +
    geom_line(aes(y = Sq), color ="blue",size=2) + 
    geom_line(aes(y = SqC), color="blue", linetype="dashed",size=2) +
    geom_line(aes(y = Sqc), color ="green",size=2) + 
    geom_line(aes(y = SqcC), color="green", linetype="dashed",size=2) +
    #Space does not appear after Latex 
    
    labs( x = "Time") +
    
    
    theme_classic(
      base_family = "",
      base_line_size = 1/22,
      base_rect_size = 1/22)+
    theme(
      axis.title.y = element_blank(),
      axis.title.x = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      #axis.title.y = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0)),
      axis.text.x  = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      axis.text.y  = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0))
    )
  
  #Necessary to close or the tikxDevice .tex file will not be written
  print(plot)
  dev.off()
}
###PART 5: A final computation of the Impact on knowledge#########


#overall drop
print((Sq[5]-SqC[5])/Sq[5])

####
#decomposition of the drop
###

deltas=Sqr[5]-Sqc[5]
deltasC=SqrC[5]-SqcC[5]


ch_c<-(SqcC[5]-Sqc[5])/(Sq[5]-SqC[5])#change in the compliant

ch_qc<-(Sm[5]/100*(deltasC-deltas))/(Sq[5]-SqC[5])#change in relative quality of censored

ch_in<-((SmC[5]-Sm[5])/100*(deltasC-deltas))/(Sq[5]-SqC[5])#interaction

ch_m<-((SmC[5]-Sm[5])/100*(deltas))/(Sq[5]-SqC[5])#change in prevalence revol.




ch_within<-((SmC[5]/100)*(Sqr[5]-SqrC[5])+(1-SmC[5]/100)*(Sqc[5]-SqcC[5]))/(SqC[5]-Sq[5])#change within

ch_int<-((Sm[5]-SmC[5])/100*(deltas-deltasC))/(SqC[5]-Sq[5])#interaction

ch_across<-((Sm[5]-SmC[5])/100*(SqrC[5])+(SmC[5]-Sm[5])/100*(SqcC[5]))/(SqC[5]-Sq[5])#change in prevalence revol.



#How much of the drop?
(SqC[5]-Sq[5])/(Sq[2]-Sq[5])


print(c((Sq[5]-SqC[5])/SqC[5],
        (Sm[5]-SmC[5])/SmC[5],
        beta,
        Sm[5]))


###PART 6: Get value functions#########
betax<-beta
source("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\calibration_censor\\vf.R") 

#Do you want the robustness graph?
if(robc){
  
#how many versions?
seqq<-rev(seq(from = 0.8, to = 0.9, by=0.1))
gpsi1<-numeric(length=length(seqq))
gpsi2<-numeric(length=length(seqq))
gmm<-numeric(length=length(seqq))
for(j in 1:length(seqq)){
  

  #Re-set imperfect censorship
  impbeta<-1/seqq[j]
  
  #Re-estimate the model
  source("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\calibration_censor\\vf1.R") 
  betax<-GA@solution[1,1]
  Sqr[1]<-GA@solution[1,6]
  Sqc[1]<-GA@solution[1,5]
  source("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\calibration_censor\\vf.R") 
  gpsi1[j]<-psi1
  gpsi2[j]<-psi2
  gmm[j]<-mt(0,exp(GA@solution[1,2]),1,1,GA@solution[1,4],Sqc[1],Sqr[1])
}
  
  #Cool graph with results
  lim.df<- data.frame(seqq,gpsi1,gpsi2,gmm)
  
  tikz(file = "lim.tex", width = 5, height = 5)
  
  #Simple plot of the dummy data using LaTeX elements
  plot <- ggplot(lim.df, aes(x = seqq)) + 
    #geom_ribbon(aes(ymin = CIq.1..., ymax = CIq.2...), fill = "red",alpha=0.15)+
    geom_line(aes(y = gpsi1), color = "blue",size=1) + 
    geom_line(aes(y = gpsi2), color="red",size=1) +
    #geom_ribbon(aes(ymin = CIq75.1..., ymax = CIq75.2...), fill = "blue",alpha=0.15)+
    #geom_line(aes(y = gmm), color = "black",size=2) + 
    #Space does not appear after Latex 
    
    labs( x = "Time", y = "Knowledge Quality") +
    
    ylim(min(gpsi1,gpsi2), max(gpsi1,gpsi2))+
    
    theme_classic(
      base_family = "",
      base_line_size = 1/22,
      base_rect_size = 1/22)+
    theme(
      axis.title.y = element_blank(),
      axis.title.x = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      #axis.title.y = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0)),
      axis.text.x  = element_text(size=18,margin = margin(t = 10, r =  0, b = 0, l = 0)),
      axis.text.y  = element_text(size=18,margin = margin(t = 0,  r = 10, b = 0, l = 0))
    )
  
  #Necessary to close or the tikxDevice .tex file will not be written
  print(plot)
  dev.off()

  
  
}
###PART 7: Bootrstrapped standard errors#########
betaB<-numeric(length=nboots)
pB<-numeric(length=nboots)
muB<-numeric(length=nboots)
thetaB<-numeric(length=nboots)
SqB<-numeric(length=nboots)
SqrB<-numeric(length=nboots)
SqcB<-numeric(length=nboots)


betaS<-numeric(length=1)
pS<-numeric(length=1)
muS<-numeric(length=1)
thetaS<-numeric(length=1)
SqS<-numeric(length=1)
SqrS<-numeric(length=1)


if(serrors & normal){
  
  for(j in 1:nboots){
    print(j)
    
    #Get bootstraped moments  
    for(i in 1:5){
      Embeta[i]=Bmbeta[i,j]
      Eqr[i]=Bqr[i,j]
      Eq[i]=Bq[i,j]
      ENC[i]=BNC[i,j]
      EqrM[i]=BqrM[i,j]
      EqM[i]=BqM[i,j]
      ENCM[i]=BNCM[i,j]
      EqrQ75[i]=Bqr75[i,j]
      EqQ75[i]=Bq75[i,j]
      ENCQ75[i]=BNC75[i,j]
    }
    
    #find the parameters for this draw  
    GA <- ga(type = "real-valued", 
             fitness = ff, 
             lower = c(0.1,1.3,1.0,0.05,3.5-0.65,Eqr[1]-0.6),
             upper = c(0.3,2.9,4  ,0.45,3.5+0.6 ,Eqr[1]+0.6),
             popSize = 100, maxiter = 180, run = 50,
             elitism = max(1, round(200*0.15)),
             optim=FALSE,
             monitor=FALSE,
             keepBest = TRUE,
             seed=1,
             optimArgs = list(method = "L-BFGS-B",poptim = 0.2,pressel = 0.2,
                              control = list(fnscale = -1, maxit = 20)))
    
    betaB[j]<-GA@solution[1,1]
    pB[j]<-exp(GA@solution[1,2])
    muB[j]<-GA@solution[1,3]
    thetaB[j]<-GA@solution[1,4]
    #SqB[j]<-GA@solution[1,5]
    #SqrB[j]<-GA@solution[1,6]
    
    SqrB[j]<-GA@solution[1,6]
    Sq[j]<-fq(thetaB[j],pB[j],GA@solution[1,5],SqrB[j])
    SqcB[j]<-GA@solution[1,5]
    
    pB[j]=pB[j]^(-thetaB[j])
    
    
    
    
  }
  
  #Compute standard errors
  betaS<-sd(betaB)
  pS<-sd(pB)
  muS<-sd(muB)
  thetaS<-sd(thetaB)
  SqrS<-sd(SqrB)
  SqcS<-sd(SqcB)
  
  #Standard Errors+other nice things for table
  kc<-(Sqc[1]/(gamma(1-theta)))^(1/theta)
  kr<-(Sqr[1]/(gamma(1-theta)))^(1/theta)
  krs<-sd((SqrB/(gamma(1-theta)))^(1/theta))
  
  

  
  #SqcB<-(SqB-muB*SqrB)/(1-muB)
  kcs<-sd((SqcB/(gamma(1-theta)))^(1/theta))
  
  #for the table
  dkc<-nchar(round(kc,digits=0))
  dkr<-nchar(round(kr,digits=0))
  dkcs<-nchar(round(kcs,digits=0))
  dkrs<-nchar(round(krs,digits=0))
  
  #kc<-kc/(10^(dkc-1))
  #kr<-kr/(10^(dkr-1))
  #kcs<-kcs/(10^(dkcs-1))
  #krs<-krs/(10^(dkrs-1))
  
  psi1s<-psi1#*1000
  psi2s<-psi2#*1000
  #Also for qc and qr
  print(c(Sqc[1],sd(SqcB)))
  print(c(Sqr[1],sd(SqrB)))
  
  #Build the tables for the paper
  sink("tempp.Rnw")
  
  cat(paste('\\begin{table}[htpb]
    \\caption{Identification of Parameters}
    \\centering % used for centering table
    \\begin{tabular}{@{\\extracolsep{5pt}}l c c c c} 
    \\hline\\hline%inserts double horizontal lines
    \\rule{-4pt}{2.5ex}
     Calibrated Parameters &  & Value & Standard Errors & Target \\\\ [0.05ex] % inserts table
     \\hline
    \\rule{-4pt}{2.5ex}
     Discount Factor  & $\\delta$   &0.06& -  &RBC literature\\\\[0.15ex]
     Fixed Cost of Censorship  & $\\hat{\\psi}$   &(\\hspace{-0.1cm}',round(psi1s, digits=3),'-',round(psi2s, digits=3),'\\hspace{-0.1cm})& - &Index set-up \\\\[0.15ex]
     \\hline % inserts single horizontal line
     \\rule{-4pt}{2.5ex}
     Estimated Parameters &  & Value & Standard Errors & Target  \\\\ [0.05ex] % inserts table
      %heading
    \\hline % inserts single horizontal line
    \\rule{-4pt}{2.5ex}
    Compliant knowledge in 1  & $k^C_1$   &',round(kc, digits=1),'&',round(kcs, digits=2),' &  $\\Omega(\\vartheta)$  \\\\[0.15ex]
    Rev. knowledge in 1  & $k^R_1$   &',round(kr, digits=1),'&',round(krs, digits=2),' & $\\Omega(\\vartheta)$ \\\\[0.15ex]
    Productivity of books  & $\\theta$   &',round(theta, digits=2),'& ',round(thetaS, digits=3),' & $\\Omega(\\vartheta)$\\\\[0.15ex]
    Max Censorship  & $\\overline{\\beta}$   &',round(beta, digits=2),'& ',round(betaS, digits=3),'& $\\Omega(\\vartheta)$\\\\[0.15ex]
    Knowledge Growth   & $(1+\\nu)\\mu$   &',round(mu, digits=2),'& ',round(muS, digits=3),' & $\\Omega(\\vartheta)$\\\\[0.15ex]
    Price of rev. books   & $p$   &',round(p^(-theta), digits=2),'& ',round(pS, digits=3),' & $\\Omega(\\vartheta)$\\\\[0.15ex]
    \\hline\\hline
    \\end{tabular}
    \\label{table:param}
    \\end{table}'))
  
  sink()
  Sweave("tempp.Rnw")
  
}


###PART 8: Final Tables#########
#Embeta<-Embeta*100




#LINE REGARDING WITH THE RESULTS

name <- paste(nome,".Rnw", sep = "")
if(normal){results<-c((Sq[5]-SqC[5])/SqC[5]*100,(Sm[5]-SmC[5])/SmC[5]*100,beta*100*impbeta,Sm[5])}
if(!normal){results<-c((Sq[5]-SqC[5])/SqC[5]*100,(Sm[5]-SmC[5])/SmC[5]*100,beta*100*impbeta,Sm[5]*100)}


sink(name)
cat(paste('&  ',round(results[1], digits=0),'\\hspace{-0.1cm}\\% & ',round(results[2], digits=0),'\\hspace{-0.1cm}\\% 
           &  ',round(results[3], digits=0),'\\hspace{-0.1cm}\\% &' ,round(results[4], digits=0),'\\hspace{-0.1cm}\\%\\\\'))
sink()
Sweave(name)

#for trying the identification
if(identif){
  setwd("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\data_work\\Fabio")
momentss<-list("Embeta"=Sm*beta/100,"Eqr"=Sqr,
               "ENC"=SNC,"Eqc"=Sqc,
               "Em"=Sm,"EqrQ75"=SqrQ75,
               "ENCQ75"=SNCQ75,"EqQ75"=SqQ75,
               "EqrM"=SqrM,"ENCM"=SNCM,
               "EqM"=SqM,"CImbeta"=CImbeta,
               "CIq"=CIq,"CIqr"=CIqr,
               "CINC"=CINC,"CIq75"=CIq75,
               "CIqr75"=CIqr75,"CINC75"=CINC75,
               "Eq"=Eq,
               "GAs"=summary(GA))

list.save(momentss, 'data.Rdata') 
}