################################################
## Calibration of the Church Censorship Model
## Authors: Blasutto Fabio and David de la Croix
################################################

###PART-1: LOAD PACKAGES########
## remove (almost) everything in the working environment.
rm(list = ls())

#increase memory size
memory.limit(size=50000)

# to import xl files
library(readxl)

#to write excel files
require(writexl)

# to output towards latex
require(stargazer)

# for generating random variables
library(evd)

# for latex symbols in the graphs
library(latex2exp)

# genetic algorithm for estimation
library(GA)

# for a bootstraped CI
library(boot)

#extract from a word
library(tidyverse)

#For fancy graphs
library(tikzDevice)
library(ggplot2)

#For list sving
library(rlist)

#Compare databases
library(compare)


#Set seed
set.seed(1)
###PART 0: WHICH SAMPLE/MODEL DO YOU WANT?#############################################
cmom<-FALSE     #want to redo-data part? 
serrors<-FALSE  #want to compute se for parameters?
nboots<-500    #Bootstrapping nummber


impbeta <<-1    #imperfectSqzr application of censorship-max 1/.86
maxper<<-5      #max number of periods to consider

ita<-FALSE      #only italian scholars
itan<-FALSE     #only northern italian scholars
itas<-FALSE     #only southern italian scholars
notonlyby<-FALSE#not only publications by person 
weak<-FALSE#do not consider weak links
identif<-FALSE  #this serves for understanding how the model is identified
robc<-FALSE

if(impbeta>1){imperfect<-TRUE}else{imperfect<-FALSE}
if(maxper<5){maxt<-TRUE}else{maxt<-FALSE}
if(ita+itan+itas+notonlyby+maxt+imperfect+weak+robc>0){normal<-FALSE}else{normal<-TRUE}

#Get name to print results
names<-c("ita","itan","itas","notonlyby","maxt","imperfect","weak","normal","robc")
valll<-c(ita,itan,itas,notonlyby,maxt,imperfect,weak,normal,robc)
namet<-which.max(valll)
nome<-names[namet]


###PART 1: GET THE DATA#############################################

  # set the directory to where the files are located
  #setwd("C:\\Users\\ddlc\\Documents\\Dropbox\\01. Research\\UTHC main\\access database")
  #setwd("C:\\Users\\blasutto\\Dropbox\\Roman_Church_censorship_growth\\big base\\old")
  setwd("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\big base")
  
  #load database 
  basew <- as.data.frame(read_excel("dictionary.xlsx"))
  basetot <- as.data.frame(read_excel("Profs.xlsx"))
  membersa  <- as.data.frame(read_excel("Italian academies.xlsx"))
  membersu  <- as.data.frame(read_excel("Italian universities.xlsx"))
  
  members<-rbind(membersa,membersu)
  #members<-as.data.frame(read_excel("Profs.xlsx"))
  basetot<-basetot[basetot$Locations_2_Country2016=="ITA",]
  
  #setwd("C:\\Users\\ddlc\\Documents\\Dropbox\\01. Research\\Roman_Church_censorship_growth\\data_work")
  setwd("C:\\Users\\Fabio\\Dropbox\\Roman_Church_censorship_growth\\data_work\\Fabio")
  #setwd("C:\\Users\\blasutto\\Dropbox\\Roman_Church_censorship_growth\\data_work")
  
  #removing people without worldcat
  members <- members[members$Worldcat!="NA",]
  basetot <- basetot[basetot$Worldcat!="NA",]
  

  members <- members[members$Forbidden!=8888,]
  basetot <- basetot[basetot$Forbidden!=8888,]


  
  
  # computing a ref date and removing people without dates
  members$refdatel <- pmin(members$Beginning,as.numeric(members$DateApprox)-5,
                           members$YearBorn+30,members$End,members$YearDied,na.rm=TRUE)
  members<- members[!is.na(members$refdatel),]
  
  basetot$refdatel <- pmin(basetot$Beginning,as.numeric(basetot$DateApprox)-5,
                           basetot$YearBorn+30,basetot$End,basetot$YearDied,na.rm=TRUE)
  basetot<- basetot[!is.na(basetot$refdatel),]
  
  #Get Nationality
  members$nation<-substring(members$BirthPlace,nchar(members$BirthPlace)-2,nchar(members$BirthPlace))
  
  
 
  #members<-members[members$nation=="ITA",]
  
  #remove duplicates
  #members$Persons_PKey<-members$PKey
  members  <- members[!duplicated(members$Persons_PKey), ]
  basew  <- basew[!duplicated(basew), ]
  #members  <- members[!members$IKey=="AcadTurin-1757",]
  members  <- members[members$refdatel>=1400,]
  members  <- members[!members$refdatel>=1751,]
  plist<-members$Persons_PKey
  
  basetot  <- basetot[!duplicated(basetot$PKey), ]
  basetot  <- basetot[basetot$refdatel>=1400,]
  basetot  <- basetot[!basetot$refdatel>=1751,]
  plist2<-basetot$PKey
  #Find the performance in the base generated by the wiki routine
  
  plist<-basetot$PKey  
  basetot$no<-0
  
  for (j in plist){
    if(sum(members$Persons_PKey==j)<1){basetot[(basetot$PKey==j),"no"] <- 1}  # for individual quality
  }
  
  
  # take the index of quality
  members$perfl <- 0
  members$bypub <- 0
  members$pubp <- 0
  members$pubb <- 0
  basetot$perfl <- 0
  basew$public<- basew$public
  #basew.pca <- prcomp(basew[,3:12], center = TRUE,scale. = TRUE)
  for (j in plist){
    members[members$Persons_PKey==j,"perfl"] <- log(max(c(basew[basew$PKey==j,"publi_by"],1)))  # for individual quality
    if(notonlyby){
      members[members$Persons_PKey==j,"perfl"] <- log(max(c(basew[basew$PKey==j,"public"],1)))
    }
    members[members$Persons_PKey==j,"pubb"] <- (c(basew[basew$PKey==j,"public"]))
    members[members$Persons_PKey==j,"bypub"] <- (c(basew[basew$PKey==j,"publi_by"]))
    members[members$Persons_PKey==j,"pubp"] <- (c(basew[basew$PKey==j,"publi_about"]))
    members[members$Persons_PKey==j,"lat"] <- (c(basetot[basetot$PKey==j,"Locations_Latitude"]))[1]
  }
  
  for (j in plist2){
    basetot[basetot$PKey==j,"perfl"] <- log(max(c(basew[basew$PKey==j,"public"],1)))  # for individual quality
    basetot[basetot$PKey==j,"bypub"] <- (c(basew[basew$PKey==j,"publi_by"])) 
  }
  
  
  #North south of italy
  if(itan){members<-members[members$lat>=43.8,]}
  if(itas){members<-members[members$lat< 43.8,]}
  
  
  members<-members[!is.na(members$perfl),]
  basetot<-basetot[!is.na(basetot$perfl),]
  
  if(!notonlyby){members<-members[members$bypub>0,]}
  if(!notonlyby){basetot<-basetot[basetot$bypub>0,]}
  
  
  plist<-basetot$PKey  
  basetot$no1<-0
  
  for (j in plist){
    if(sum(members$Persons_PKey==j)<1){basetot[(basetot$PKey==j),"no1"] <- 1}  # for individual quality
  }
  
  ################################################
  # PART 2: COMPUTE THE MOMENTS
  ################################################
  
  #We consider 5 periods here
  members  <- members[members$refdatel>1400,]
  members  <- members[!members$refdatel>=1751,]
  
  
  
  
  
  threshold0<- 1400
  threshold1 <- 1470
  threshold2 <- 1540
  threshold3 <- 1610
  threshold4<-1680
  threshold5<-1750
  
  members  <- members[members$refdatel>=threshold0,]
  members  <- members[!members$refdatel>threshold5,]
  
  members$censored<-0
  members$censored[members$Forbidden<8888]<-1
  
  members1 <- members[members$refdatel<threshold1,]
  members2 <- members[threshold2>members$refdatel & members$refdatel>=threshold1,]
  members3 <- members[threshold3>members$refdatel & members$refdatel>=threshold2,]
  members4 <- members[threshold4>members$refdatel & members$refdatel>=threshold3,]
  members5 <- members[members$refdatel>=threshold4,]
  
  
  #Best per period
  l1<-sort(members1$perfl, index.return=TRUE, decreasing=TRUE)
  th1<-min(lapply(l1, `[`, l1$x %in% head(unique(l1$x),10))$x)
  top1<-mean(members1[members1$perfl>=th1,]$censored)
  
  l2<-sort(members2$perfl, index.return=TRUE, decreasing=TRUE)
  th2<-min(lapply(l2, `[`, l2$x %in% head(unique(l2$x),10))$x)
  top2<-mean(members2[members2$perfl>=th2,]$censored)
  
  l3<-sort(members3$perfl, index.return=TRUE, decreasing=TRUE)
  th3<-min(lapply(l3, `[`, l3$x %in% head(unique(l3$x),10))$x)
  top3<-mean(members3[members3$perfl>=th3,]$censored)
  
  l4<-sort(members4$perfl, index.return=TRUE, decreasing=TRUE)
  th4<-min(lapply(l4, `[`, l4$x %in% head(unique(l4$x),10))$x)
  top4<-mean(members4[members4$perfl>=th4,]$censored)
  
  l5<-sort(members5$perfl, index.return=TRUE, decreasing=TRUE)
  th5<-min(lapply(l5, `[`, l5$x %in% head(unique(l5$x),10))$x)
  top5<-mean(members5[members5$perfl>=th5,]$censored)


